[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "sequencer"
version = "1.0.0"
requires-python = ">=3.10"

[project.optional-dependencies]
dev = [
   "pytest"
]